# Site settings
title: Thore Petersen
author:
  name: ""
description: ""

# Build settings
remote_theme: thorepet/minima

minima:
  hide_site_feed_link: true
  social_links:
    - title: "GitHub"
      icon: github
      url: "https://github.com/thorepet"
    - title: "LinkedIn"
      icon: linkedin
      url: "https://www.linkedin.com/in/thore-petersen-013b431ba"
